### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by crackers8199** [fHDHR/fHDHR_plugin_origin_locast#24]
is this dead? i can't get it to log in, i keep getting 403...

[2021-08-04 22:01:51,161] ERROR - Login Failed: 403 Client Error: Forbidden for url: https://api.locastnet.org/api/user/login

**Comment by crackers8199** [comment]
seems this probably has something to do with it...
https://www.reddit.com/r/locast/comments/oxuc6g/locast_has_broken_the_api/

**Comment by deathbybandaid** [comment]
I'm on vacation and just reading about this now, I'll try to work on a fix this next week

**Comment by deathbybandaid** [comment]
Pasting here for future me


https://github.com/tgorgdotcom/locast2plex/issues/272#issuecomment-893012492

https://github.com/wouterdebie/locast2tuner/commit/28379cba9ef3b4c6989c23f0f80c2cc353078c35

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR_plugin_origin_locast/pull/25

**Comment by fouticus** [comment]
Just tested, I can log in successfully now. Thanks!
