### ISSUE TITLE
Locast is temperately suspended.

### ISSUE THREAD

**Issue by CHJ85** [fHDHR/fHDHR_plugin_origin_locast#33]
Hi there. Locast ended their services last week and will most likely not return until after all the court and legal circus next year. So if I were you, I'd hide this repo for the time being.
And btw, USTVGO made changes to their API. Please have a look at that one as well and add the missing channels such as Boomerang.
And could you look into adding USTVNow? Unrelated paid service.
And also please look into LocalBTV. This one is an up and coming alternative to Locast.
Thanks for all your great work.

**Comment by deathbybandaid** [comment]
I put a note on Readme.md that this plugin won't work anymore.

**Comment by deathbybandaid** [comment]
Requests for new origin plugins can be done in the main repo
